### ISSUE TITLE
Still in development?

### ISSUE THREAD

**Issue by leotrs** [FedericoCeratto/shoebill#3]
This seems like an awesome project, is it still in development?

**Comment by FedericoCeratto** [comment]
Thank you @leotrs - the basic features are implemented and I'm not working on adding new ones at the moment, but I'm open to PRs, bug reports and feature requests!

**Comment by elec3647** [comment]
Love this idea. Would love to use with Python 3. I made the switch and would love to run this with python 2

**Comment by FedericoCeratto** [comment]
Version 1.0.0 is released with Python 3 support. Enjoy!
